import PageHeader from '@/Components/PageHeader';
import ProgressBar from '@/Components/ProgressBar';
import StatusBadge from '@/Components/StatusBadge';
import AuthenticatedLayout from '@/Layouts/AuthenticatedLayout';
import { formatDate } from '@/utils';
import { Head, router, useForm } from '@inertiajs/react';
import { useState } from 'react';

/**
 * One submission pack: what the platform answered, what the officer still has
 * to, what was excluded as unverified, and where it sits in the chain of
 * three people who have to touch it before it can be filed.
 */
export default function Show({ pack, definition, threshold = 95, can = {}, blockedBecause = [] }) {
    const sections = pack.content?.sections ?? [];
    const [open, setOpen] = useState(sections[0]?.key ?? null);

    const answers = useForm({ answers: {} });

    const setAnswer = (key, value) => answers.setData('answers', { ...answers.data.answers, [key]: value });

    const save = () => answers.put(route('submissions.update', pack.id), {
        preserveScroll: true,
        onSuccess: () => answers.setData('answers', {}),
    });

    const blocking = (pack.validation_errors ?? []).filter((error) => error.blocking !== false);
    const advisory = (pack.validation_errors ?? []).filter((error) => error.blocking === false);

    return (
        <AuthenticatedLayout header={pack.pack_ref}>
            <Head title={`${pack.pack_type} — ${pack.period_label}`} />

            <PageHeader
                title={definition?.label ?? pack.pack_type}
                subtitle={`${pack.pack_ref} · ${pack.period_label}`}
                breadcrumbs={[
                    { label: 'Submissions', href: route('submissions.index') },
                    { label: pack.pack_ref },
                ]}
                actions={
                    <>
                        <a href={`${route('submissions.download', pack.id)}?format=pdf`} className="btn-secondary">
                            PDF
                        </a>
                        <a href={`${route('submissions.download', pack.id)}?format=docx`} className="btn-secondary">
                            Word
                        </a>
                        <Actions pack={pack} can={can} />
                    </>
                }
            />

            {/* ── The chain, always visible ─────────────────────────────── */}
            <section className="card mb-4">
                <div className="card-body grid grid-cols-1 gap-4 sm:grid-cols-2 lg:grid-cols-5">
                    <Fact label="Status"><StatusBadge status={pack.status} /></Fact>
                    <Fact label="Generated by">{pack.generator?.name ?? '—'}</Fact>
                    <Fact label="Reviewed by">{pack.reviewer?.name ?? 'Not yet reviewed'}</Fact>
                    <Fact label="Approved by">{pack.approver?.name ?? 'Not yet approved'}</Fact>
                    <Fact label="Filed">
                        {pack.submitted_at
                            ? `${formatDate(pack.submitted_at)}${pack.submission_reference ? ` · ${pack.submission_reference}` : ''}`
                            : 'Not filed'}
                    </Fact>
                </div>

                <div className="border-t border-gray-100 px-5 py-4">
                    <div className="mb-1 flex items-baseline justify-between text-sm">
                        <span className="text-[var(--color-text-secondary)]">Completeness</span>
                        <span className="font-semibold tabular-nums">
                            {pack.completeness_score}% <span className="text-xs font-normal text-gray-400">of {threshold}% required</span>
                        </span>
                    </div>
                    <ProgressBar
                        value={pack.completeness_score}
                        color={pack.completeness_score >= threshold ? '#0CA30C' : '#FAB219'}
                    />
                </div>

                {pack.checksum && (
                    <p className="border-t border-gray-100 px-5 py-2 font-mono text-[10px] text-gray-400">
                        Locked {formatDate(pack.locked_at)} · SHA-256 {pack.checksum}
                    </p>
                )}
            </section>

            {blockedBecause.length > 0 && (
                <p className="mb-4 rounded-lg border border-blue-200 bg-blue-50 px-4 py-2 text-sm text-blue-800">
                    {blockedBecause.join(' ')}
                </p>
            )}

            {blocking.length > 0 && (
                <Notices
                    tone="error"
                    title="Blocking — this pack cannot be filed until these are resolved"
                    items={blocking.map((error) => error.message)}
                />
            )}

            {advisory.length > 0 && (
                <Notices
                    tone="warning"
                    title="Advisory"
                    items={advisory.map((error) => error.message)}
                />
            )}

            {(pack.unverified_items ?? []).length > 0 && (
                <section className="card mb-4">
                    <div className="card-header">
                        <h2 className="text-sm font-semibold">
                            Excluded as unverified ({pack.unverified_items.length})
                        </h2>
                    </div>
                    <div className="overflow-x-auto">
                        <table className="data-table">
                            <thead>
                                <tr>
                                    <th>Reference</th>
                                    <th>Item</th>
                                    <th>Status</th>
                                    <th>Why it was excluded</th>
                                </tr>
                            </thead>
                            <tbody>
                                {pack.unverified_items.map((item, index) => (
                                    <tr key={index}>
                                        <td className="font-mono text-xs">{item.ref}</td>
                                        <td>{item.title}</td>
                                        <td>{item.status}</td>
                                        <td className="text-xs text-[var(--color-text-secondary)]">{item.reason}</td>
                                    </tr>
                                ))}
                            </tbody>
                        </table>
                    </div>
                </section>
            )}

            {/* ── The return itself ─────────────────────────────────────── */}
            {sections.map((section) => (
                <section key={section.key} className="card mb-4">
                    <button
                        type="button"
                        className="card-header w-full text-left"
                        onClick={() => setOpen(open === section.key ? null : section.key)}
                        aria-expanded={open === section.key}
                    >
                        <h2 className="text-sm font-semibold">{section.title}</h2>
                        <span className="text-xs text-gray-400">
                            {section.fields.filter((field) => field.required).length} required · {open === section.key ? 'Hide' : 'Show'}
                        </span>
                    </button>

                    {open === section.key && (
                        <div className="card-body space-y-4">
                            {section.fields.map((field) => (
                                <FieldRow
                                    key={field.key}
                                    field={field}
                                    section={section}
                                    editable={can.update}
                                    value={answers.data.answers[field.key] ?? field.value}
                                    onChange={(value) => setAnswer(field.key, value)}
                                />
                            ))}
                        </div>
                    )}
                </section>
            ))}

            {can.update && (
                <div className="sticky bottom-4 flex justify-end">
                    <button
                        type="button"
                        onClick={save}
                        disabled={answers.processing || Object.keys(answers.data.answers).length === 0}
                        className="btn-primary shadow-lg"
                    >
                        Save answers
                    </button>
                </div>
            )}
        </AuthenticatedLayout>
    );
}

function FieldRow({ field, section, editable, value, onChange }) {
    const isSystem = field.source === 'system';
    const rowHeadings = section.row_templates?.[field.key];

    if (Array.isArray(field.value) || Array.isArray(value)) {
        const rows = Array.isArray(value) ? value : [];

        return (
            <div>
                <p className="form-label">
                    {field.label}
                    {field.required && <span className="ms-1 text-[var(--color-error)]">*</span>}
                </p>
                {field.note && <p className="mb-1 text-xs text-[var(--color-text-secondary)]">{field.note}</p>}

                {rows.length === 0 ? (
                    <p className="text-sm text-gray-400">Nothing recorded.</p>
                ) : (
                    <div className="overflow-x-auto">
                        <table className="data-table">
                            {rowHeadings && (
                                <thead>
                                    <tr>{rowHeadings.map((heading) => <th key={heading}>{heading}</th>)}</tr>
                                </thead>
                            )}
                            <tbody>
                                {rows.map((row, index) => (
                                    <tr key={index}>
                                        {(Array.isArray(row) ? row : [row]).map((cell, cellIndex) => (
                                            <td key={cellIndex}>{cell === null || cell === '' ? '—' : String(cell)}</td>
                                        ))}
                                    </tr>
                                ))}
                            </tbody>
                        </table>
                    </div>
                )}
            </div>
        );
    }

    return (
        <div>
            <label className="form-label" htmlFor={`field-${field.key}`}>
                {field.label}
                {field.required && <span className="ms-1 text-[var(--color-error)]">*</span>}
                {isSystem && <span className="ms-2 badge badge-status-active">From the platform</span>}
            </label>

            {isSystem || !editable ? (
                <p className="rounded-lg bg-gray-50 px-3 py-2 text-sm text-[var(--color-text-primary)]">
                    {value === null || value === '' ? '—' : String(value)}
                </p>
            ) : field.options?.length ? (
                <select
                    id={`field-${field.key}`}
                    className="form-select"
                    value={value ?? ''}
                    onChange={(event) => onChange(event.target.value)}
                >
                    <option value="">Not answered</option>
                    {field.options.map((option) => (
                        <option key={option} value={option}>{option}</option>
                    ))}
                </select>
            ) : (
                <textarea
                    id={`field-${field.key}`}
                    className="form-input"
                    rows={2}
                    value={value ?? ''}
                    onChange={(event) => onChange(event.target.value)}
                />
            )}

            {field.note && <p className="mt-1 text-xs text-[var(--color-text-secondary)]">{field.note}</p>}
        </div>
    );
}

function Actions({ pack, can }) {
    if (can.sendForReview) {
        return (
            <button
                type="button"
                onClick={() => router.post(route('submissions.send-for-review', pack.id))}
                className="btn-primary"
            >
                Send for review
            </button>
        );
    }

    if (can.review) {
        const decide = (decision) => {
            const notes = decision === 'return'
                ? window.prompt('What needs correcting before this goes back for approval?')
                : null;

            if (decision === 'return' && !notes) {
                return;
            }

            router.post(route('submissions.review', pack.id), { decision, notes });
        };

        return (
            <>
                <button type="button" onClick={() => decide('return')} className="btn-secondary">
                    Return to draft
                </button>
                <button type="button" onClick={() => decide('accept')} className="btn-primary">
                    Mark reviewed
                </button>
            </>
        );
    }

    if (can.approve) {
        return (
            <button
                type="button"
                onClick={() => router.post(route('submissions.approve', pack.id))}
                className="btn-primary"
            >
                Approve and lock
            </button>
        );
    }

    if (can.file) {
        return (
            <button
                type="button"
                onClick={() => router.post(route('submissions.file', pack.id), {
                    submission_reference: window.prompt('Regulator submission reference (optional)') ?? '',
                })}
                className="btn-primary"
            >
                Record as filed
            </button>
        );
    }

    if (can.acknowledge) {
        return (
            <button
                type="button"
                onClick={() => {
                    const reference = window.prompt('Acknowledgement reference');

                    if (reference) {
                        router.post(route('submissions.acknowledge', pack.id), { acknowledgement_ref: reference });
                    }
                }}
                className="btn-primary"
            >
                Record acknowledgement
            </button>
        );
    }

    return null;
}

function Fact({ label, children }) {
    return (
        <div>
            <dt className="text-xs uppercase tracking-wide text-gray-400">{label}</dt>
            <dd className="mt-1 text-sm text-[var(--color-text-primary)]">{children}</dd>
        </div>
    );
}

function Notices({ tone, title, items }) {
    const styles = tone === 'error'
        ? 'border-red-200 bg-red-50 text-red-800'
        : 'border-amber-200 bg-amber-50 text-amber-800';

    return (
        <section className={`mb-4 rounded-lg border px-4 py-3 text-sm ${styles}`}>
            <p className="font-semibold">{title}</p>
            <ul className="mt-1 list-disc space-y-1 ps-5">
                {items.map((item, index) => <li key={index}>{item}</li>)}
            </ul>
        </section>
    );
}
